/*
 * Module: pipeline_regs_tb_wrap
 * Purpose: Test wrapper that exposes all Stage-02 pipeline registers for cocotb.
 * Interface: Flattened per-stage control/data inputs and observed outputs.
 * Behavior: Instantiates IF/ID, ID/EX, EX/MEM, and MEM/WB registers.
 * Reset: Shared active-high synchronous reset for all instantiated registers.
 * Pipeline control: Each register has independent stall/flush inputs.
 * Corner cases: Enables explicit verification of flush-over-stall priority per stage.
 */
module pipeline_regs_tb_wrap (
    input  logic        clk,
    input  logic        rst,

    input  logic        if_id_stall,
    input  logic        if_id_flush,
    input  logic [63:0] if_id_pc_in,
    input  logic [31:0] if_id_instr_in,
    input  logic        if_id_valid_in,
    output logic [63:0] if_id_pc_out,
    output logic [31:0] if_id_instr_out,
    output logic        if_id_valid_out,

    input  logic        id_ex_stall,
    input  logic        id_ex_flush,
    input  logic [63:0] id_ex_pc_in,
    input  logic [63:0] id_ex_rs1_data_in,
    input  logic [63:0] id_ex_rs2_data_in,
    input  logic [63:0] id_ex_imm_in,
    input  logic [6:0]  id_ex_opcode_in,
    input  logic [4:0]  id_ex_rd_in,
    input  logic [4:0]  id_ex_rs1_addr_in,
    input  logic [4:0]  id_ex_rs2_addr_in,
    input  logic [2:0]  id_ex_funct3_in,
    input  logic [6:0]  id_ex_funct7_in,
    input  logic [3:0]  id_ex_alu_op_in,
    input  logic        id_ex_alu_src_in,
    input  logic        id_ex_mem_read_in,
    input  logic        id_ex_mem_write_in,
    input  logic        id_ex_reg_write_in,
    input  logic        id_ex_mem_to_reg_in,
    input  logic        id_ex_branch_in,
    input  logic        id_ex_jump_in,
    input  logic        id_ex_is_word_op_in,
    input  logic        id_ex_valid_in,
    output logic [63:0] id_ex_pc_out,
    output logic [63:0] id_ex_rs1_data_out,
    output logic [63:0] id_ex_rs2_data_out,
    output logic [63:0] id_ex_imm_out,
    output logic [6:0]  id_ex_opcode_out,
    output logic [4:0]  id_ex_rd_out,
    output logic [4:0]  id_ex_rs1_addr_out,
    output logic [4:0]  id_ex_rs2_addr_out,
    output logic [2:0]  id_ex_funct3_out,
    output logic [6:0]  id_ex_funct7_out,
    output logic [3:0]  id_ex_alu_op_out,
    output logic        id_ex_alu_src_out,
    output logic        id_ex_mem_read_out,
    output logic        id_ex_mem_write_out,
    output logic        id_ex_reg_write_out,
    output logic        id_ex_mem_to_reg_out,
    output logic        id_ex_branch_out,
    output logic        id_ex_jump_out,
    output logic        id_ex_is_word_op_out,
    output logic        id_ex_valid_out,

    input  logic        ex_mem_stall,
    input  logic        ex_mem_flush,
    input  logic [63:0] ex_mem_pc_in,
    input  logic [63:0] ex_mem_alu_result_in,
    input  logic [63:0] ex_mem_rs2_data_in,
    input  logic [4:0]  ex_mem_rd_in,
    input  logic [2:0]  ex_mem_funct3_in,
    input  logic        ex_mem_mem_read_in,
    input  logic        ex_mem_mem_write_in,
    input  logic        ex_mem_reg_write_in,
    input  logic        ex_mem_mem_to_reg_in,
    input  logic        ex_mem_is_word_op_in,
    input  logic        ex_mem_branch_taken_in,
    input  logic [63:0] ex_mem_branch_target_in,
    input  logic        ex_mem_valid_in,
    output logic [63:0] ex_mem_pc_out,
    output logic [63:0] ex_mem_alu_result_out,
    output logic [63:0] ex_mem_rs2_data_out,
    output logic [4:0]  ex_mem_rd_out,
    output logic [2:0]  ex_mem_funct3_out,
    output logic        ex_mem_mem_read_out,
    output logic        ex_mem_mem_write_out,
    output logic        ex_mem_reg_write_out,
    output logic        ex_mem_mem_to_reg_out,
    output logic        ex_mem_is_word_op_out,
    output logic        ex_mem_branch_taken_out,
    output logic [63:0] ex_mem_branch_target_out,
    output logic        ex_mem_valid_out,

    input  logic        mem_wb_stall,
    input  logic        mem_wb_flush,
    input  logic [63:0] mem_wb_alu_result_in,
    input  logic [63:0] mem_wb_mem_data_in,
    input  logic [4:0]  mem_wb_rd_in,
    input  logic        mem_wb_reg_write_in,
    input  logic        mem_wb_mem_to_reg_in,
    input  logic        mem_wb_valid_in,
    output logic [63:0] mem_wb_alu_result_out,
    output logic [63:0] mem_wb_mem_data_out,
    output logic [4:0]  mem_wb_rd_out,
    output logic        mem_wb_reg_write_out,
    output logic        mem_wb_mem_to_reg_out,
    output logic        mem_wb_valid_out
);
    if_id_reg u_if_id_reg (
        .clk(clk),
        .rst(rst),
        .stall(if_id_stall),
        .flush(if_id_flush),
        .pc_in(if_id_pc_in),
        .instr_in(if_id_instr_in),
        .valid_in(if_id_valid_in),
        .pc_out(if_id_pc_out),
        .instr_out(if_id_instr_out),
        .valid_out(if_id_valid_out)
    );

    id_ex_reg u_id_ex_reg (
        .clk(clk),
        .rst(rst),
        .stall(id_ex_stall),
        .flush(id_ex_flush),
        .pc_in(id_ex_pc_in),
        .rs1_data_in(id_ex_rs1_data_in),
        .rs2_data_in(id_ex_rs2_data_in),
        .imm_in(id_ex_imm_in),
        .opcode_in(id_ex_opcode_in),
        .rd_in(id_ex_rd_in),
        .rs1_addr_in(id_ex_rs1_addr_in),
        .rs2_addr_in(id_ex_rs2_addr_in),
        .funct3_in(id_ex_funct3_in),
        .funct7_in(id_ex_funct7_in),
        .alu_op_in(id_ex_alu_op_in),
        .alu_src_in(id_ex_alu_src_in),
        .mem_read_in(id_ex_mem_read_in),
        .mem_write_in(id_ex_mem_write_in),
        .reg_write_in(id_ex_reg_write_in),
        .mem_to_reg_in(id_ex_mem_to_reg_in),
        .branch_in(id_ex_branch_in),
        .jump_in(id_ex_jump_in),
        .is_word_op_in(id_ex_is_word_op_in),
        .valid_in(id_ex_valid_in),
        .pc_out(id_ex_pc_out),
        .rs1_data_out(id_ex_rs1_data_out),
        .rs2_data_out(id_ex_rs2_data_out),
        .imm_out(id_ex_imm_out),
        .opcode_out(id_ex_opcode_out),
        .rd_out(id_ex_rd_out),
        .rs1_addr_out(id_ex_rs1_addr_out),
        .rs2_addr_out(id_ex_rs2_addr_out),
        .funct3_out(id_ex_funct3_out),
        .funct7_out(id_ex_funct7_out),
        .alu_op_out(id_ex_alu_op_out),
        .alu_src_out(id_ex_alu_src_out),
        .mem_read_out(id_ex_mem_read_out),
        .mem_write_out(id_ex_mem_write_out),
        .reg_write_out(id_ex_reg_write_out),
        .mem_to_reg_out(id_ex_mem_to_reg_out),
        .branch_out(id_ex_branch_out),
        .jump_out(id_ex_jump_out),
        .is_word_op_out(id_ex_is_word_op_out),
        .valid_out(id_ex_valid_out)
    );

    ex_mem_reg u_ex_mem_reg (
        .clk(clk),
        .rst(rst),
        .stall(ex_mem_stall),
        .flush(ex_mem_flush),
        .pc_in(ex_mem_pc_in),
        .alu_result_in(ex_mem_alu_result_in),
        .rs2_data_in(ex_mem_rs2_data_in),
        .rd_in(ex_mem_rd_in),
        .funct3_in(ex_mem_funct3_in),
        .mem_read_in(ex_mem_mem_read_in),
        .mem_write_in(ex_mem_mem_write_in),
        .reg_write_in(ex_mem_reg_write_in),
        .mem_to_reg_in(ex_mem_mem_to_reg_in),
        .is_word_op_in(ex_mem_is_word_op_in),
        .branch_taken_in(ex_mem_branch_taken_in),
        .branch_target_in(ex_mem_branch_target_in),
        .valid_in(ex_mem_valid_in),
        .pc_out(ex_mem_pc_out),
        .alu_result_out(ex_mem_alu_result_out),
        .rs2_data_out(ex_mem_rs2_data_out),
        .rd_out(ex_mem_rd_out),
        .funct3_out(ex_mem_funct3_out),
        .mem_read_out(ex_mem_mem_read_out),
        .mem_write_out(ex_mem_mem_write_out),
        .reg_write_out(ex_mem_reg_write_out),
        .mem_to_reg_out(ex_mem_mem_to_reg_out),
        .is_word_op_out(ex_mem_is_word_op_out),
        .branch_taken_out(ex_mem_branch_taken_out),
        .branch_target_out(ex_mem_branch_target_out),
        .valid_out(ex_mem_valid_out)
    );

    mem_wb_reg u_mem_wb_reg (
        .clk(clk),
        .rst(rst),
        .stall(mem_wb_stall),
        .flush(mem_wb_flush),
        .alu_result_in(mem_wb_alu_result_in),
        .mem_data_in(mem_wb_mem_data_in),
        .rd_in(mem_wb_rd_in),
        .reg_write_in(mem_wb_reg_write_in),
        .mem_to_reg_in(mem_wb_mem_to_reg_in),
        .valid_in(mem_wb_valid_in),
        .alu_result_out(mem_wb_alu_result_out),
        .mem_data_out(mem_wb_mem_data_out),
        .rd_out(mem_wb_rd_out),
        .reg_write_out(mem_wb_reg_write_out),
        .mem_to_reg_out(mem_wb_mem_to_reg_out),
        .valid_out(mem_wb_valid_out)
    );
endmodule
